SWM-E2I/wemeet-backend

.github/workflows/ci.yml
#1
* ci 작업에 대한 workflow에 develop 브랜치를 추가하였습니다.
=> build(ci): add develop branch to ci workflow

build.gradle, src/main/resources/application.yml
#5 
* flyway는 DB 형상관리도구입니다.
* `/resources/db/migration` 아래 `V${version}__{description}.sql` 파일을 통해 관리합니다.
* `ex. V2306202332__create_member.sql`
=> build(gradle): add settings for flyway

.github/workflows/cd.yml, build.gradle
=> build(cd): build-cd-pipeline

.github/workflows/cd.yml, task-definition.json
#30 
* ECS에 배포하는 과정을 자동화하는 Github Actions Job을 추가합니다.
=> build(cd): add ecs deploy pipeline

build.gradle, src/main/java/com/e2i/wemeet/config/common/JpaConfig.java
#40 
QueryDsl 사용을 위한 세팅을 추가하였습니다.
=> build(gradle): add queryDsl settings

src/main/java/com/e2i/wemeet/controller/member/MemberController.java, src/main/java/com/e2i/wemeet/service/code/CodeService.java, src/main/java/com/e2i/wemeet/service/code/CodeServiceImpl.java, src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java, src/test/java/com/e2i/wemeet/service/code/CodeServiceTest.java
None
memberController에서 사용하던 findCode 함수를 codeService로 분리해 CodeList를 사용하는 다른 Controller에서도 동일하게 사용할 수 있도록 변경하였습니다.
=> refactor(code): separate find code funtion to code servie

src/test/java/com/e2i/wemeet/config/security/filter/SMSLoginProcessingFilterTest.java, src/test/java/com/e2i/wemeet/controller/credential/CredentialControllerTest.java, src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java
None
controller test에 작성된 api docs tag를 공통된 API끼리 묶어주었습니다.
=> refactor(api-docs): change api docs tag

src/main/java/com/e2i/wemeet/controller/member/MemberController.java, src/main/java/com/e2i/wemeet/dto/response/member/RoleResponseDto.java, src/main/java/com/e2i/wemeet/service/member/MemberService.java, src/main/java/com/e2i/wemeet/service/member/MemberServiceImpl.java, src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java, src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java
None
* member의 Role과 팀 여부를 확인할 수 있는 API를 추가하였습니다.
=> feat(member): add get member role api

src/main/java/com/e2i/wemeet/controller/team/TeamController.java, src/main/java/com/e2i/wemeet/domain/teampreferencemeetingtype/TeamPreferenceMeetingType.java, src/main/java/com/e2i/wemeet/exception/ErrorCode.java, src/main/java/com/e2i/wemeet/exception/badrequest/ManagerSelfDeletionException.java, src/main/java/com/e2i/wemeet/exception/badrequest/NonTeamMemberException.java, src/main/java/com/e2i/wemeet/service/team/TeamService.java, src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java, src/main/resources/db/migration/V2306211524__create_team.sql, src/main/resources/messages.properties, src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java, src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
#48 
팀 삭제 및 팀원 삭제 API를 추가하였습니다.
=> feat(team): add team delete api

.github/workflows/cd.yml, build.gradle
#57 
plugin을 사용하여 project 버전 변경 후 한번 더 develop 브랜치에 push 하는 작업을 삭제하고 image tag에 대한 Job을 추가하였습니다.
=> build(gradle): modify container image tag

.github/workflows/cd.yml, docker-compose.yml, src/main/resources/application.yml
#28 
* AWS EC2에 docker compose를 사용하여 개발 서버를 배포합니다.
=> build(cd): build cd pipeline

src/main/java/com/e2i/wemeet/dto/request/member/CreateMemberRequestDto.java, src/main/java/com/e2i/wemeet/service/member/MemberService.java, src/main/java/com/e2i/wemeet/service/member/MemberServiceImpl.java, src/main/java/com/e2i/wemeet/util/RandomCodeUtils.java, src/main/java/com/e2i/wemeet/util/aspect/TokenInjectionAspect.java, src/test/java/com/e2i/wemeet/controller/member/MemberControllerTest.java, src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java, src/test/java/com/e2i/wemeet/util/aspect/TokenInjectionAspectTest.java
=> refactor(member): refactory the member registration api

src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java, src/test/java/com/e2i/wemeet/service/team/TeamInvitationServiceTest.java, src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java
#70 
테스트 코드에서 사용한 junit 함수를 assertj 함수로 수정하였습니다.
=> refactor(test): change junit to assertj

src/main/java/com/e2i/wemeet/domain/code/CodePk.java, src/main/java/com/e2i/wemeet/domain/code/CodeRepository.java, src/main/java/com/e2i/wemeet/security/model/MemberPrincipal.java, src/main/java/com/e2i/wemeet/security/provider/SmsUserDetailsService.java, src/main/java/com/e2i/wemeet/service/code/CodeServiceImpl.java, src/main/java/com/e2i/wemeet/util/validator/CustomFormatValidator.java, src/test/java/com/e2i/wemeet/config/security/filter/SmsLoginProcessingFilterTest.java, src/test/java/com/e2i/wemeet/domain/code/CodeRepositoryTest.java, src/test/java/com/e2i/wemeet/domain/member/MemberRepositoryTest.java, src/test/java/com/e2i/wemeet/service/admin/TestServiceTestAuthorization.java, src/test/java/com/e2i/wemeet/service/code/CodeServiceTest.java, src/test/java/com/e2i/wemeet/service/member/MemberServiceTest.java, src/test/java/com/e2i/wemeet/util/validator/CustomFormatValidatorTest.java
#83 
- Test가 실패하는 부분에 대한 코드를 수정하였습니다. 
- Code 관련 로직을 수정하였습니다.
- 프론트로부터 전송받은 코드 포맷을 검증할 수 있는 validator를 추가하였습니다. "CE-001"
=> fix(test): make test red to green

build.gradle, src/main/java/com/e2i/wemeet/config/log/LogFilter.java, src/main/java/com/e2i/wemeet/config/log/aspect/ControllerLogAspect.java, src/main/java/com/e2i/wemeet/config/log/aspect/ServiceLogAspect.java, src/main/resources/application.yml, src/main/resources/logback-spring.xml
- log framework 를 log4j2 logback으로 변경합니다.
=> refactor(log): change log framework

src/main/java/com/e2i/wemeet/controller/team/TeamController.java, src/main/java/com/e2i/wemeet/domain/team/Team.java, src/main/java/com/e2i/wemeet/dto/request/team/CreateTeamRequestDto.java, src/main/java/com/e2i/wemeet/dto/request/team/UpdateTeamRequestDto.java, src/main/java/com/e2i/wemeet/dto/response/team/MyTeamDetailResponseDto.java, src/main/java/com/e2i/wemeet/dto/response/team/MyTeamResponseDto.java, src/main/java/com/e2i/wemeet/service/team/TeamService.java, src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java, src/main/resources/db/migration/V2306211524__create_team.sql, src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java, src/test/java/com/e2i/wemeet/service/team/TeamServiceTest.java, src/test/java/com/e2i/wemeet/support/fixture/TeamFixture.java
=> refactor(team): add chatLink to team creation request data

src/main/java/com/e2i/wemeet/service/member_image/MemberImageServiceImpl.java, src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
#118
이미지 url을 cloudFront url로 변경하였습니다.
=> chore(image): change saved url from s3 domain to cloudfront domain

src/main/java/com/e2i/wemeet/service/member_image/MemberImageServiceImpl.java, src/main/java/com/e2i/wemeet/service/team/TeamServiceImpl.java
#118 
이미지 저장 url의 도메인을 cloudFront로 변경하였습니다.
=> refactor(image): change image url from s3 to cloudFront

src/main/java/com/e2i/wemeet/controller/heart/HeartController.java, src/main/java/com/e2i/wemeet/dto/response/heart/ReceivedHeartResponseDto.java, src/main/java/com/e2i/wemeet/dto/response/heart/SentHeartResponseDto.java, src/main/java/com/e2i/wemeet/service/heart/HeartService.java, src/main/java/com/e2i/wemeet/service/heart/HeartServiceImpl.java, src/test/java/com/e2i/wemeet/controller/heart/HeartControllerTest.java, src/test/java/com/e2i/wemeet/service/heart/HeartServiceTest.java
none
보낸 좋아요 조회 API의 결과를 List로 수정하였습니다.
=> refactor(heart): change api response to list

src/main/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImpl.java, src/main/java/com/e2i/wemeet/dto/dsl/TeamInformationDto.java, src/main/java/com/e2i/wemeet/dto/response/team/TeamDetailResponseDto.java, src/main/resources/static/swagger-ui/openapi3.yaml, src/test/java/com/e2i/wemeet/controller/team/TeamControllerTest.java, src/test/java/com/e2i/wemeet/domain/team/TeamCustomRepositoryImplTest.java
- 팀 상세 정보 조회에 카카오톡 채팅 링크를 추가합니다.
=> refactor(team): add chatlink to read team detail api
